// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWJhU1S1KSkGGaE5j5NXItckqGgT8eJyw',
    appId: '1:1036021868367:web:bd93d8300d3926637d073a',
    messagingSenderId: '1036021868367',
    projectId: 'quick-slice-e7905',
    authDomain: 'quick-slice-e7905.firebaseapp.com',
    storageBucket: 'quick-slice-e7905.firebasestorage.app',
    measurementId: 'G-SDNT54KLKC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLGpBmLl5T_VIv4dp6-BqP_D-mBAQSPVM',
    appId: '1:1036021868367:android:c0162f2913a3b1277d073a',
    messagingSenderId: '1036021868367',
    projectId: 'quick-slice-e7905',
    storageBucket: 'quick-slice-e7905.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcedXiPhZZEMchX6jzq3uCnFeWtfGp1Sk',
    appId: '1:1036021868367:ios:fd9177bc01e5319b7d073a',
    messagingSenderId: '1036021868367',
    projectId: 'quick-slice-e7905',
    storageBucket: 'quick-slice-e7905.firebasestorage.app',
    iosBundleId: 'com.example.quickSlice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcedXiPhZZEMchX6jzq3uCnFeWtfGp1Sk',
    appId: '1:1036021868367:ios:fd9177bc01e5319b7d073a',
    messagingSenderId: '1036021868367',
    projectId: 'quick-slice-e7905',
    storageBucket: 'quick-slice-e7905.firebasestorage.app',
    iosBundleId: 'com.example.quickSlice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWJhU1S1KSkGGaE5j5NXItckqGgT8eJyw',
    appId: '1:1036021868367:web:34e2f79d05ab7e447d073a',
    messagingSenderId: '1036021868367',
    projectId: 'quick-slice-e7905',
    authDomain: 'quick-slice-e7905.firebaseapp.com',
    storageBucket: 'quick-slice-e7905.firebasestorage.app',
    measurementId: 'G-8N4DGYTGQQ',
  );

}